# Phoenix Project - AI Ensemble & Fusion Engine Configuration
# -----------------------------------------------------------
# This file centralizes all parameters for the AI "Jury" and the "Judge".

# 1. Ensemble Client Definitions
clients:
  analyst:
    enable: true
    model_name: "gemini-1.5-pro-latest"
    api_key_env_var: "GEMINI_API_KEY"
    prompt_template: "ai/prompts/analyst.json"
    timeout_seconds: 90
    max_concurrent: 5
    temperature: 0.1
    health_probes:
      failure_threshold: 3
      cooldown_minutes: 15

  fact_checker:
    enable: true
    model_name: "gemini-1.5-flash-latest"
    api_key_env_var: "GEMINI_API_KEY"
    prompt_template: "ai/prompts/fact_checker.json"
    timeout_seconds: 60
    max_concurrent: 10
    temperature: 0.2
    health_probes:
      failure_threshold: 5
      cooldown_minutes: 10

# 2. Evidence Fusion Engine Settings
fusion_engine:
  dispersion_threshold: 0.15
  min_avg_evidence_score: 0.35
  conservative_fallback_factor: 1.0
  clamp_min: 0.7
  clamp_max: 1.3
  weight_floor: 0.1
  
  type_weights:
    sec_filing: 1.0
    analyst_rating: 0.8
    news: 0.7
    market_data: 0.9
    research: 0.9
    other: 0.5
  
  source_reputation:
    "SEC": 1.0
    "WSJ": 0.9
    "Reuters": 0.9
    "Bloomberg": 0.9
    "Fed Reserve": 1.0

# 3. Human Review & Alerting Thresholds
human_review:
  dispersion_alert_threshold: 0.30
  max_allocation_change_for_auto: 0.3

# 4. Global Settings
audit_log_retention_days: 30
