# Phoenix_project/config.yaml
# Global configuration for the Phoenix Project trading system

# System-wide settings
system:
  environment: "development" # "production" or "development"
  log_level: "INFO"
  
# Configuration for data sources
data_manager:
  data_cache_dir: "data_cache"
  hot_tier_days: 365 # Data within the last year is considered "hot"
  data_providers:
    # List of data providers, ordered by default priority
    - name: "primary_provider"
      api_key: "YOUR_API_KEY"
      priority: 1 # Fallback priority
      cost_per_request: 0.01 # Cost in USD per API call
      daily_limit: 1000 # Max requests per day
    - name: "alternative_provider"
      api_key: "YOUR_ALT_KEY"
      priority: 2
      incremental_updates: true # Enable/disable intelligent fetching
      cost_per_request: 0.05
      daily_limit: 500

# Feature store configuration
feature_store:
  sma_period: 50
  rsi_period: 14

# Position sizer configuration
position_sizer:
  type: "volatility_parity" # or "fixed_fraction"
  parameters:
    volatility_period: 20
    risk_target: 0.02 # Target 2% risk per position
    
# Strategy handler configuration
strategy_handler:
  strategy_name: "MomentumStrategy"

# Execution layer configuration
execution:
  broker: "backtesting" # "interactive_brokers" or "backtesting"
  commission: 0.001
  initial_cash: 100000.0

# AI Cognitive Engine settings
cognitive_engine:
  prediction_model_path: "models/prediction_model.joblib"
