# 1. General Configuration
project_name: "Phoenix Project"
version: "2.0.0"
description: "An advanced AI-driven quantitative trading framework."
log_level: "INFO" # DEBUG, INFO, WARNING, ERROR, CRITICAL

# 2. Strategy Parameters
asset_universe: ["SPY", "QQQ", "GLD", "TLT", "VWO"]
max_total_allocation: 0.95 # Max % of portfolio value to be invested
commission_rate: 0.0005 # 0.05%
sma_period: 50
rsi_period: 14
rsi_overbought_threshold: 70.0
opportunity_score_threshold: 55.0

# [NEW] 3. Risk Management (Dynamic Risk Budgeting)
risk_manager:
  max_uncertainty: 0.05       # Uncertainty level at which capital modifier hits minimum
  min_capital_modifier: 0.1   # The floor for the capital modifier

# 4. Cerebro Engine Settings
initial_cash: 1000000.0

# 5. Data Sources Configuration
data_sources:
  start_date: "2018-01-01"
  end_date: "2023-12-31"
  cache_dir: "data_cache"
  # Configuration for each data provider
  providers:
    tiingo:
      api_key_env_var: "TIINGO_API_KEY"
      # Higher number means higher priority
      priority: 10
    yfinance:
      priority: 5

# 6. Position Sizing Settings
position_sizer:
  method: "volatility_parity" # Can be "fixed_fraction" or "volatility_parity"
  parameters:
    volatility_period: 20 # Lookback period for volatility calculation

# 7. AI Configuration
ai_mode: "processed" # "live", "processed", or "off"
ai_clients_config_path: "config/ai_clients.yaml"
# Path to a directory where pre-computed AI analyses are stored/loaded from.
# If a path is provided, the system will use cached data if it exists for the given dates.
# If the path is null, analyses will be re-computed live (incurs API costs).
ai_analysis_snapshot_dir: "ai_snapshots"

# 8. Execution Model Configuration
execution_model:
  impact_coefficient: 0.1     # Price impact constant for slippage model
  max_volume_share: 0.25      # Max % of a bar's volume an order can consume
  min_trade_notional: 1.0     # Minimum trade notional value
  average_spread_bps: 1.5     # Assumed avg bid-ask spread in basis points (0.015%)

# [NEW] 9. Data Quality Monitoring (DQM) Settings
data_quality_monitoring:
  completeness_threshold: 0.98 # Require at least 98% of close prices to be non-null
  staleness_days_threshold: 3  # Data's latest point cannot be older than 3 days from run time
  price_change_std_dev_threshold: 5.0 # Reject data if daily change > 5 std devs from the mean

# [NEW] 10. Market State Prediction Model
market_state_predictor:
  long_term_ma: 200
  threshold: 0.05
  model_params:
    n_estimators: 100
    learning_rate: 0.1
