# Phoenix Project - Strategy Configuration
# ------------------------------------------
# This file centralizes all parameters for the backtest.

# 1. Backtest Timeframe & Universe
start_date: 2022-01-01
end_date: 2024-12-31
asset_universe:
  - 'QQQ'
  - 'SPY'
  - 'GLD'
  - 'TLT'
  - 'IWM'

# 1.5. Market Breadth Tickers
market_breadth_tickers:
  - 'SPY'
  - 'QQQ'
  - 'AAPL'
  - 'MSFT'
  - 'GOOGL'
  - 'AMZN'
  - 'NVDA'
  - 'TSLA'

# 2. Strategy Parameters
sma_period: 50
rsi_period: 14
rsi_overbought_threshold: 70.0
opportunity_score_threshold: 55.0

# 3. Risk Management Parameters (VIX-based)
vix_high_threshold: 30.0
vix_low_threshold: 20.0
capital_modifier_high_vix: 0.5
capital_modifier_normal_vix: 0.9
capital_modifier_low_vix: 1.0

# 4. Cerebro Engine Settings
initial_cash: 1000000.0
commission_rate: 0.001
log_level: "INFO"

# 5. Gemini AI Advisor Settings
gemini_config:
  enable: true
  mode: "mock"
  api_key_env_var: "GEMINI_API_KEY"
  model_name: "gemini-1.5-flash-latest"
  request_timeout: 90
  audit_log_retention_days: 30 # Set to 0 to disable cleanup
  max_concurrent_requests: 5  # Max parallel requests to the API
  prompts:
    market_sentiment: >
      你是一位专业的金融市场分析师。请分析以下今天的财经新闻标题，并以-1.0（极度悲观）到+1.0（极度乐观）的范围给出一个总体的市场情绪得分。
      请仅返回一个符合规范的JSON对象，格式为：{"sentiment_score": <得分>, "reasoning": "<简要分析理由>"}.
      新闻标题：
      {headlines}
    asset_analysis: >
      分析资产 {ticker} 最近的重大新闻、财报预期或分析师评级。是否存在任何可能在短期内影响其价格的、非技术性的积极或消极因素？
      请给出一个调整系数，范围从0.5（有重大利空）到1.5（有重大利好），正常情况为1.0。同时，请提供一个0.0（完全不确定）到1.0（非常确定）之间的可信度评分。
      请仅返回一个符合规范的JSON对象，格式为：{"adjustment_factor": <系数>, "confidence": <可信度>, "reasoning": "<简要分析理由>"}.
    batch_asset_analysis: >
      你是一位专业的金融市场分析师。请对以下资产列表进行独立的定性分析：{tickers}。
      对每一个资产，请评估其短期内的非技术性积极或消极因素，并提供一个调整系数（0.5-1.5）和可信度评分（0.0-1.0）。
      请仅返回一个符合规范的、单一的JSON对象，其中每个键是资产的ticker，值是其对应的分析对象。
      例如: {{"QQQ": {{"adjustment_factor": 1.1, "confidence": 0.8, "reasoning": "..."}}, "SPY": {{...}} }}
    summary_report: >
      你是一位名为'凤凰元帅'的AI交易模型的总指挥。请根据以下整个回测周期的表现和关键决策数据，撰写一份给项目主管的“战后总结报告”。报告需要用指挥官的口吻，分析策略的优势、劣劣势，并解释在关键时间点（如市场大跌时）我们是如何利用VIX和宏观情绪分析来调整风险敞口的。
      你的分析需要富有洞察力且易于理解。
      回测数据:
      {metrics}

# 6. Execution & Experimentation Settings
ai_mode: "processed"
max_total_allocation: 0.95

# 7. Walk-Forward Optimization Settings
walk_forward:
  enabled: true
  # 所有值均为日历日
  train_days: 730  # 约2年用于训练
  test_days: 365   # 约1年用于样本外验证
  step_days: 365   # 将窗口向前滑动1年

# 8. Execution Model Settings
execution_model:
  impact_coefficient: 0.1     # Price impact constant for slippage model
  max_volume_share: 0.25      # Max % of a bar's volume an order can consume

# 9. Position Sizing Settings
position_sizer:
  method: "fixed_fraction" # Available: "fixed_fraction", "volatility_parity"
  parameters:
    fraction_per_position: 0.10 # Allocate 10% to each selected asset

# 10. Optimizer Settings
optimizer:
  study_name: "phoenix_walk_forward_study"
  n_trials: 50 # Number of optimization trials per walk-forward window
  parameters:
    sma_period:
      type: "int"
      low: 30
      high: 80
      step: 10
    rsi_period:
      type: "int"
      low: 10
      high: 20
      step: 2

# 11. Observability Settings
observability:
  metrics_port: 8000 # Port for the Prometheus metrics server

# 12. Audit & Compliance Settings
audit:
  s3_bucket_name: "your-phoenix-project-audit-logs-bucket" # S3 bucket for archiving AI audit logs
