"""
Defines the core schema for Evidence, which is the standardized output
of all L1 Agents.
"""

from pydantic import BaseModel, Field, condecimal
from typing import Optional, Dict, Any, List
from datetime import datetime
from enum import Enum
import uuid

class EvidenceType(str, Enum):
    """
    Enumeration of the types of evidence an L1 Agent can produce.
    """
    FUNDAMENTAL = "Fundamental"
    TECHNICAL = "Technical"
    CATALYST = "Catalyst"
    MACRO = "Macro"
    GEOPOLITICAL = "Geopolitical"
    SUPPLY_CHAIN = "SupplyChain"
    INNOVATION = "Innovation"
    GENERIC = "Generic"

class EvidenceItem(BaseModel):
    """
    A single piece of raw evidence generated by an L1 Agent.
    This is the primary data structure passed from L1 to L2.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique identifier for the evidence item.")
    agent_id: str = Field(..., description="The ID of the L1 agent that generated this evidence (from registry.yaml).")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Timestamp (UTC) of when the evidence was generated.")
    symbols: List[str] = Field(..., description="List of asset symbols (e.g., ['AAPL', 'MSFT']) this evidence pertains to.")
    
    evidence_type: EvidenceType = Field(..., description="The category of the evidence.")
    content: str = Field(..., description="The core textual analysis or finding from the agent.")
    confidence: condecimal(ge=0.0, le=1.0) = Field(..., description="Agent's confidence in this evidence (0.0 to 1.0).")
    
    data_horizon: str = Field(..., description="The signal horizon this evidence is relevant for (e.g., 'Short-Term', 'Long-Term').")
    
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Supporting data, e.g., data snippets, source URLs, chart coordinates.")

    class Config:
        frozen = True
        json_encoders = {
            datetime: lambda v: v.isoformat(),
        }
